version: '3'

services:
  stratum-relay1:
    build: .
    container_name: stratum-relay
    restart: unless-stopped
    command:  python3 strelay.py -s gate.emcd.io -t 3333 -u bkbtw.001 -a x -l 0.0.0.0 -p 3334
    ports:
      - "3301:3334"